---
# tasks file for mysql_db
    - name: Install MySQL database
      apt: 
       name: "{{ item }}"
       state: present
       with_items:
        - mysql-server
        - mysql-client

    - name: start MySQL service
      service:
       name: mysql
       state: started
       enabled: yes

    - name: Create Application Database
      mysql_db: 
       name: employee_db 
       state: present

    - name: creare mysql_user
      mysql_user:
       name: db_user
       password: Passw0rd
       priv: '*.*:ALL'
       state: present
       host: '%'